---
title: "Factors and Categorical Data"
author: "Jason Pemberton"
date: "2025-04-07"
output: html_document
---

Reordering levels of factors using ***forcats***

Manually reordering:  
By the value of the factor  
By the average value of another variable  
By lumping  
By reversing order  
By collapsing

------------------------------------------------------------------------

```{r Load Libraries, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(forcats)
library(patchwork)
```

---

```{r EDA, echo=FALSE, message=FALSE, warning=FALSE}
View(gss_cat)
glimpse(gss_cat)
# The order of categorical variables matters

unique(gss_cat$race)

# or

gss_cat %>% 
  pull(race) %>% # pull the race variable out as a vector, as opposed to as a data.frame
  unique() # requires a vector

# count 
count(gss_cat, race, sort = T) # 1st argument is data.frame, second is the variable, sorted biggest to smallest

gss_cat %>% 
  select(race) %>% 
  table()


gss_cat %>% 
  mutate(race = fct_drop(race)) %>% 
  pull(race) %>% 
  levels()

```

---

```{r Order Factor by Another Variable, echo=FALSE, message=FALSE, warning=FALSE}
# We'd like to order religion BY average TV watching time

gss_cat %>% 
  drop_na(tvhours) %>% 
  group_by(relig) %>% 
  summarise(mean_tv = mean(tvhours)) %>% 
  ggplot(aes(mean_tv, relig)) +
  geom_point(size = 4) +
  labs(
    title = "Average TV Viewing Hours by Religion",
    x = "Avg. Viewing Hours",
    y = "Religion"
  )

# to create the same result using mutate:
# gss_cat %>% 
#   drop_na(tvhours) %>% 
#   group_by(relig) %>% 
#   mutate(mean_tv = mean(tvhours)) %>% 
#   distinct(relig, mean_tv) %>% 
#   ggplot(aes(mean_tv, relig)) +
#   geom_point(size = 4)

gss_cat %>% 
  drop_na(tvhours) %>% 
  group_by(relig) %>% 
  summarise(mean_tv = mean(tvhours)) %>% 
  mutate(relig = fct_reorder(relig, mean_tv)) %>% 
  ggplot(aes(mean_tv, relig)) +
  geom_point(size = 4) +
  labs(
    title = "Average TV Viewing Hours by Religion",
    x = "Avg. Viewing Hours",
    y = "Religion"
  )
```

---

```{r Reverse Factor Levels, echo=FALSE, message=FALSE, warning=FALSE}
gss_cat %>% 
  drop_na(age) %>% 
  filter(rincome != "Not applicable") %>% 
  group_by(rincome) %>% 
  summarise(mean_age = mean(age)) %>%
  ggplot(aes(mean_age, rincome)) +
  geom_point(size = 4) +
  labs(
    title = "Income by Avg. Age",
    x = "Average Age",
    y = "Income Level"
  )


gss_cat %>% 
  drop_na(age) %>% 
  filter(rincome != "Not applicable") %>% 
  group_by(rincome) %>% 
  summarise(mean_age = mean(age)) %>%
  mutate(rincome = fct_rev(rincome)) %>% 
  ggplot(aes(mean_age, rincome)) +
  geom_point(size = 4) +
  labs(
    title = "Income by Avg. Age",
    x = "Average Age",
    y = "Income Level"
  )
```

---

```{r Order Factor Levels by Freq. of Variable Value, echo=FALSE, message=FALSE, warning=FALSE}

# Original Plot
gss_cat %>% 
  ggplot(aes(marital)) +
  geom_bar()

# frequency count
gss_cat %>% 
  mutate(marital = fct_infreq(marital)) %>% # frequency count
  count(marital)

# reverse frequency count
gss_cat %>% 
  mutate(marital = fct_infreq(marital)) %>% # frequency count
  mutate(marital = fct_rev(marital)) %>% # reverse frequency count
  count(marital)

# Visualize
gss_cat %>% 
  mutate(marital = marital %>% fct_infreq() %>% fct_rev()) %>% 
  ggplot(aes(marital)) +
  geom_bar(fill = "steelblue", alpha = 0.5) +
  theme_bw()
```

---

```{r Recode Factors, echo=FALSE, message=FALSE, warning=FALSE}
gss_cat %>% 
  mutate(partyid = fct_recode(partyid,
                              "Republican, strong" = "Strong republican",
                              "Republican, weak" = "Not str republican",
                              "Independent, near rep" = "Ind, near rep",
                              "Independent, near dem" = "Ind, near dem",
                              "Democrat, weak" = "Not str democrat",
                              "Democrat, strong" = "Strong democrat",
                              "Other" = "No answer",
                              "Other" = "Don't know",
                              "Other" = "Other party"
                              )) %>% 
  count(partyid)

# Alternative method - Factor Collapse
gss_cat %>% 
  mutate(partyid = fct_collapse(partyid,
                                other = c("No answer", "Don't know", "Other party"),
                                rep = c("Strong republican", "Not str republican"),
                                ind = c("Ind, near rep", "Ind, near dem"),
                                dem = c("Not str democrat", "Strong democrat"))) %>% 
  count(partyid)

# lumping into other
gss_cat %>% 
  count(relig, sort = T)

gss_cat %>% 
  mutate(relig = fct_lump(relig, n=2)) %>% # lumps results into top to, and all others
  count(relig)
```

---

```{r Reorder Factor "y" by Value Corresponding to Largest "X", echo=FALSE, message=FALSE, warning=FALSE}

gss_cat %>% 
  filter(!is.na(age)) %>% 
  filter(marital %in% c(
    "Never married",
    "Married",
    "Widowed")) %>% 
  count(age, marital) %>% 
  group_by(age) %>% 
  mutate(prop = (n / sum(n)) * 100) %>% 
  ggplot(aes(age, prop, colour = marital)) +
  geom_line(size = 2, na.rm = TRUE) +
  theme_minimal() +
  labs(
    title = "Proportion of Marriage Status by Age",
    x = "Age",
    y = "Percent"
  )

# by default the legend is ordered as a factor. Lets rearrange so the colour of the
# legend is displayed to match the order of the lines at the end of the chart.

gss_cat %>% 
  filter(!is.na(age)) %>% 
  filter(marital %in% c(
    "Never married",
    "Married",
    "Widowed")) %>% 
  count(age, marital) %>% 
  group_by(age) %>% 
  mutate(prop = (n / sum(n)) * 100) %>% 
  mutate(marital = fct_reorder2(marital, age, prop)) %>% 
  mutate(marital = fct_rev(marital)) %>% 
  ggplot(aes(age, prop, colour = marital)) +
  geom_line(size = 1, na.rm = TRUE) +
  theme_minimal() +
  labs(
    title = "Proportion of Marriage Status by Age",
    x = "Age",
    y = "Percent"
  )
```

