---
title: "Maps"
author: "Jason Pemberton"
format: html
editor: visual
---

## Quarto

```{r}
#| label: Load Libraries
#| message: false
#| warning: false
#| include: false
library(tidyverse)
library(sf)
library(ggthemes)
library(rnaturalearth)
```

```{r}
#| label: Generate data frmae
#| message: false
#| warning: false
#| include: false
world <- ne_countries(scale = "medium",
                      returnclass = "sf")
```

```{r}
#| label: Visualize - World Income
#| echo: true
#| message: false
#| warning: false
world %>% 
  ggplot(aes(fill = income_grp)) +
  geom_sf() +
  labs(
    title = "World Map by Income Group",
    fill = "Income Group"
  ) +
  scale_fill_viridis_d() +
  theme_map() +
  theme(
    legend.position = "right",
    legend.title =  element_text(face = "bold"),
    plot.title = element_text(size = 20,
                              colour = "steelblue",
                              hjust = 0.5,
                              face = "bold"))
```

```{r}
#| label: Visualize - Africa Population
#| echo: true
#| message: false
#| warning: false

world %>% 
  filter(region_un == "Africa") %>% 
  ggplot() +
  geom_sf(aes(fill = pop_est/1e6),
          color = "white",
          lwd = 0.3) +
  labs(
    title = "Africa Population Size",
    fill = "Population\n(millions)") +
  theme_map() +
    theme(
        legend.position = "top",
        legend.title = element_text(face = "bold"),
        legend.key.width = unit(1.4, "cm"), # Comma instead of +
        plot.title = element_text(
            size = 16,
            colour = "steelblue",
            hjust = 0.5,
            face = "bold"
        )
    )


```

```{r}
#| label: Visualize - Brazil HDI
#| echo: true
#| message: false
#| warning: false

atlas <- read_rds("https://github.com/viniciusoike/restateinsight/raw/main/static/data/atlas_sp_hdi.rds")

ggplot(atlas) +
  geom_sf(aes(fill = HDI),
          lwd = 0.02,
          color = "white") +
  scale_fill_fermenter(
    name = "HDI Scores",
    breaks = seq(0.65, 0.95, 0.05),
    direction =1,
    palette = "YlGnBu") +
  labs(title = "HDI in Sao Palo, Brazil (2010") +
  theme_map() +
  theme(
    legend.position = "right",  # Legend placed at the bottom
    legend.title = element_text(face = "bold"),
    legend.key.width = unit(1.4, "cm"),
    plot.title = element_text(
      size = 9,
      colour = "steelblue",
      hjust = 0.5,
      face = "bold"
    )
  )

```
