---
title: "ggplot - Advanced 1"
author: "Jason Pemberton"
date: "2025-04-15"
output: html_document
---

Visualizing Difference in Faculty Salaries by Rank and Gender

```{r Load Libraries, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(car)
library(scales)

theme_set(theme_bw())
```

------------------------------------------------------------------------

```{r EDA, echo=FALSE, message=FALSE, warning=FALSE}
head(Salaries)
```

------------------------------------------------------------------------

```{r Visualize Scatterplot, echo=FALSE, message=FALSE, warning=FALSE}
Salaries %>% 
  ggplot(aes(yrs.since.phd, salary, colour = rank)) +
  geom_point()
```

Tidy up the plot by:\
1. Make shape = discipline\
2. Change geom_point to geom_jitter (add small amount of noise to avoid overlap of points)\
3. Add linear model \~ sex\
4. Facet by sex\
5. Add axis and legend labels

```{r Revised Visualize, echo=FALSE, message=FALSE, warning=FALSE}
Salaries %>% 
  ggplot(aes(yrs.since.phd, salary)) +
  geom_jitter(aes(colour = rank, shape = discipline)) + # moving the colour and rank here only applies to the jitter, not geom_smooth
  geom_smooth(method = lm) +
  facet_wrap(~sex) +
  labs(
    title = "Salary vs Years Since PhD",
    x = "Years Since PhD",
    y = "Income",
    color = "Position", # control legend label rather than default
    shape = "Research Area" # control legend label rather than default
  ) +
  scale_y_continuous(labels = label_dollar())


```

------------------------------------------------------------------------

Boxplots

```{r Visualize Boxplot, echo=FALSE, message=FALSE, warning=FALSE}
Salaries %>% 
  filter(salary < 1500000) %>% 
  ggplot(aes(rank, salary, fill = sex)) +
  geom_boxplot(alpha = 0.5) +
  scale_x_discrete(breaks = c("AsstProf",
                              "AssocProf",
                              "Prof"),
                   labels = c("Assistant\nProfessor",
                              "Associate\nProfessor",
                              "Full\nProfessor")) +
  scale_y_continuous(breaks = c(50000, 100000, 150000, 200000),
                     labels = c("$50K", "$100K", "$150K", "$200K")) +
  labs(
    title = "Faculty Salary by Rank and Gender",
    x = "",
    y = "Salary"
  ) +
  theme(legend.position = c(0.11, 0.78))
```
