---
title: "ggplot - Titles and Annotation"
author: "Jason Pemberton"
date: "2025-04-22"
output: html_document
---

```{r Load Libraries, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
```

---

```{r VIsualize, echo=FALSE, message=FALSE, warning=FALSE}
mtcars %>% 
  ggplot(aes(wt, mpg, colour = factor(gear))) +
  geom_point(size = 3, alpha = 0.6) +
  labs(
    title = "Weight vs Miles per Gallon",
    x = "Weight",
    y = "Miles per Gallon",
    colour = "Gears") +
  theme_bw() +
  theme(plot.title = 
          element_text(size = 18,
                       face = "bold",
                       colour = "steelblue",
                       hjust = 0.5),
        axis.title = 
          element_text(size = 12,
                       color = "steelblue")) +
  theme(legend.position = c(0.9,0.8)) +
  annotate("text", x = 4, y = 30,
           label = "Notice the difference\n between cars with\n three and four gears",
           colour = "black") +
  geom_segment(x = 4.4, y = 25, xend = 4.7, yend = 16,
               arrow = arrow(length = unit(0.7, "cm")),
               colour = "red",
               size = 1.5) +
  geom_segment(x = 3.4, y = 30, xend = 2.4, yend = 30,
               arrow = arrow(length = unit(0.7, "cm")),
               colour = "green",
               size = 1.5)
```

