---
title: "Visualization - Part 6"
author: "Jason Pemberton"
date: "2025-03-12"
output: html_document
---

Load Libraries  

```{r Load Libraries, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
```

---

Bar Charts  

```{r Bar Chart, echo=FALSE}

starwars %>% 
  filter(hair_color == "black" | hair_color == "brown") %>% 
  drop_na(sex) %>% 
  ggplot(aes(hair_color, fill = sex)) +
  geom_bar(position = "dodge", # or "fill"or leave blank
           alpha = 0.5)+
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  labs(title = "Gender and Hair Colour",
       x = "Hair Colour",
       y = "Number")
  
```

---

```{r Bar Chart with Facet Wrap, echo=FALSE, message=FALSE, warning=FALSE}

starwars %>% 
  filter(hair_color %in% c("black","brown")) %>%
  drop_na(sex) %>% 
  ggplot(aes(sex)) +
  geom_bar(aes(fill = sex), alpha = 0.5) +
  facet_wrap(~ hair_color) +
  theme_bw() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        legend.position = "none") +
  labs(title = "Gender and Hair Colour",
       x = "Hair Colour",
       y = "Number")

```